# Generated by Django 2.0.6 on 2018-06-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profileplayers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePlayers',
        ),
    ]
